language: csharp
solution: build/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
install:
  - ./cmake.sh
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
