language: csharp
solution: Cryptonite.Yaal.sln
os: windows
install:
  - cmake -S ./src -B ./build
  - nuget restore ./build/Cryptonite.Yaal.sln
script:
  - msbuild /p:Configuration=Release ./build/Cryptonite.Yaal.sln
