language: csharp
solution: build/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
before_install:
  # solution generation not support on CMake under Linux - need to create solution directly
  - dotnet new sln --name Cryptonite.Yacl
  - dotnet sln Cryptonite.Yacl.sln add src/Cryptonite.Yacl.Common/Cryptonite.Yacl.Common.csproj
  - dotnet sln Cryptonite.Yacl.sln add src/Cryptonite.Yacl.GZip/Cryptonite.Yacl.GZip.csproj
  - dotnet sln Cryptonite.Yacl.sln add src/Cryptonite.Yacl.Tests.Common/Cryptonite.Yacl.Tests.Common.csproj
  - dotnet sln Cryptonite.Yacl.sln add src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
