language: csharp
solution: Cryptonite.Yaal.sln
dist: bionic
install:
  - mkdir -p ./build
  - pushd ./build
  - cmake ../src
  - popd
  - nuget restore ./build/Cryptonite.Yaal.sln
script:
  - msbuild /p:Configuration=Release ./build/Cryptonite.Yaal.sln
