language: csharp
solution: build/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
before_install:
  - mkdir -p tools
  - pushd tools
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.tar.gz
  - tar zxf cmake-3.19.2-Linux-x86_64.tar.gz
  - popd
install:
  - PATH=$PWD/tools/cmake-3.19.2-Linux-x86_64/bin:$PATH ./cmake.sh
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
