language: csharp
solution: src/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
before_install:
  # build native libraries beforehand
  - mkdir -p lib/build
  - pushd lib/build
  - cmake -S ..
  - cmake --build .
  - popd
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
