language: csharp
solution: src/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
before_install:
  # build native libraries beforehand
  - pushd lib/bzip2
  - ./cmake.sh
  - popd
  - pushd lib/xz-utils
  - ./cmake.sh
  - popd
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
