language: csharp
solution: src/Cryptonite.Yacl.sln
dist: bionic
mono: none
dotnet: 3.1
before_install:
  # download newer version of CMake - these are required for some of the native libraries
  - mkdir -p tools
  - pushd tools
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.tar.gz
  - tar zxf cmake-3.19.2-Linux-x86_64.tar.gz
  - CMAKE_PATH=$PWD/cmake-3.19.2-Linux-x86_64
  - popd
  # build native libraries beforehand
  - pushd lib/bzip2
  - PATH=$CMAKE_PATH/bin:$PATH ./cmake.sh
  - popd
  - pushd lib/xz-utils
  - PATH=$CMAKE_PATH/bin:$PATH ./cmake.sh
  - popd
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test src/Cryptonite.Yacl.Tests.GZip/Cryptonite.Yacl.Tests.GZip.csproj
