using System;

namespace Cryptonite.Yacl.Tests.Common
{
    public class TestResources
    {
        public const String LoremIpsum = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat semper viverra nam libero justo laoreet sit amet. Urna molestie at elementum eu facilisis sed odio morbi. Praesent tristique magna sit amet purus gravida. Mattis nunc sed blandit libero volutpat sed. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Pellentesque elit ullamcorper dignissim cras. Enim neque volutpat ac tincidunt vitae. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Urna duis convallis convallis tellus id interdum. Quam id leo in vitae turpis massa sed elementum. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Massa sed elementum tempus egestas sed. Elit sed vulputate mi sit amet mauris. Luctus accumsan tortor posuere ac ut. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant.

Vestibulum morbi blandit cursus risus at ultrices mi tempus. Purus sit amet volutpat consequat mauris. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Bibendum est ultricies integer quis auctor. Ipsum consequat nisl vel pretium lectus quam id leo. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Vel facilisis volutpat est velit egestas dui id. Sit amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Sit amet risus nullam eget felis eget. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum.

Arcu ac tortor dignissim convallis aenean et tortor at. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Velit euismod in pellentesque massa placerat. Tortor condimentum lacinia quis vel. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Sed faucibus turpis in eu mi bibendum neque egestas. Duis ultricies lacus sed turpis tincidunt id aliquet. Amet volutpat consequat mauris nunc. Tortor at auctor urna nunc. Sed faucibus turpis in eu mi bibendum. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Ipsum dolor sit amet consectetur adipiscing elit pellentesque.

Vulputate ut pharetra sit amet aliquam id. Mi bibendum neque egestas congue quisque egestas diam in. Lectus magna fringilla urna porttitor rhoncus dolor purus non. In dictum non consectetur a erat nam. Lacus suspendisse faucibus interdum posuere lorem. Id volutpat lacus laoreet non curabitur gravida. Molestie at elementum eu facilisis sed odio. Sollicitudin tempor id eu nisl nunc mi ipsum. Purus in mollis nunc sed. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Rhoncus est pellentesque elit ullamcorper dignissim. Dui ut ornare lectus sit amet. Nullam vehicula ipsum a arcu cursus vitae congue.

Est pellentesque elit ullamcorper dignissim cras. Convallis aenean et tortor at risus viverra. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Tincidunt nunc pulvinar sapien et ligula. Magna sit amet purus gravida. Urna neque viverra justo nec ultrices dui sapien. Ac turpis egestas integer eget aliquet. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Suspendisse in est ante in nibh mauris cursus. Phasellus egestas tellus rutrum tellus. Id donec ultrices tincidunt arcu non sodales neque. Risus at ultrices mi tempus imperdiet nulla. Semper auctor neque vitae tempus quam pellentesque nec nam. Consequat semper viverra nam libero justo laoreet sit. Libero justo laoreet sit amet cursus sit amet dictum sit. Amet facilisis magna etiam tempor. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Malesuada fames ac turpis egestas maecenas. Id ornare arcu odio ut sem nulla pharetra diam sit.

Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Massa tempor nec feugiat nisl pretium. Dignissim sodales ut eu sem. Magnis dis parturient montes nascetur ridiculus mus. Id faucibus nisl tincidunt eget nullam non nisi est. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Viverra vitae congue eu consequat ac felis donec et. Dictum fusce ut placerat orci nulla pellentesque dignissim enim. Sodales ut etiam sit amet. Id consectetur purus ut faucibus pulvinar. Ornare arcu odio ut sem nulla. Tempor nec feugiat nisl pretium fusce id velit ut.

Integer feugiat scelerisque varius morbi enim. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Netus et malesuada fames ac turpis egestas. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Mauris pharetra et ultrices neque ornare aenean euismod. Maecenas volutpat blandit aliquam etiam erat velit. Quam nulla porttitor massa id. Rhoncus aenean vel elit scelerisque. Leo urna molestie at elementum eu facilisis sed. Elit eget gravida cum sociis natoque. In cursus turpis massa tincidunt dui ut ornare lectus sit. Senectus et netus et malesuada fames ac turpis egestas. Fames ac turpis egestas maecenas pharetra convallis posuere. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Eget lorem dolor sed viverra ipsum nunc. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. A cras semper auctor neque vitae tempus quam. Convallis posuere morbi leo urna molestie at elementum eu.

Urna neque viverra justo nec ultrices dui. Tempus imperdiet nulla malesuada pellentesque. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Quis viverra nibh cras pulvinar mattis nunc. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Lectus arcu bibendum at varius vel pharetra vel. Auctor neque vitae tempus quam pellentesque nec nam aliquam sem. Tristique nulla aliquet enim tortor at auctor urna. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Arcu odio ut sem nulla pharetra diam sit. Dolor sit amet consectetur adipiscing elit. Tempus iaculis urna id volutpat. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Tincidunt id aliquet risus feugiat in.

Sagittis orci a scelerisque purus. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Sed viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Dui id ornare arcu odio ut. In nulla posuere sollicitudin aliquam ultrices sagittis. Nulla facilisi morbi tempus iaculis urna id volutpat. Blandit massa enim nec dui nunc mattis enim ut tellus. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Vitae congue eu consequat ac felis donec. Posuere ac ut consequat semper. Eget aliquet nibh praesent tristique magna sit amet purus. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Est ante in nibh mauris cursus. Eu nisl nunc mi ipsum faucibus vitae aliquet. Sit amet massa vitae tortor condimentum lacinia quis vel. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida.

Cursus sit amet dictum sit amet justo donec enim. Id faucibus nisl tincidunt eget. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Egestas dui id ornare arcu odio. Imperdiet massa tincidunt nunc pulvinar sapien. Etiam sit amet nisl purus in mollis nunc. Viverra orci sagittis eu volutpat odio facilisis mauris. Odio pellentesque diam volutpat commodo sed egestas. Massa ultricies mi quis hendrerit dolor magna. Egestas erat imperdiet sed euismod nisi porta lorem mollis. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Non quam lacus suspendisse faucibus interdum posuere. Dui nunc mattis enim ut tellus. Condimentum lacinia quis vel eros donec ac odio tempor.

Id donec ultrices tincidunt arcu non sodales neque sodales ut. Diam sit amet nisl suscipit. Morbi tempus iaculis urna id volutpat lacus laoreet non. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tortor consequat id porta nibh venenatis cras sed. Auctor urna nunc id cursus. Ut tellus elementum sagittis vitae et. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Accumsan tortor posuere ac ut consequat semper. Tellus at urna condimentum mattis pellentesque. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tellus molestie nunc non blandit massa enim nec dui nunc. Massa enim nec dui nunc mattis enim. Laoreet sit amet cursus sit amet dictum. Velit scelerisque in dictum non consectetur a erat nam at. In nisl nisi scelerisque eu ultrices vitae. Consectetur libero id faucibus nisl tincidunt eget. Tempor orci eu lobortis elementum nibh tellus.

Facilisi etiam dignissim diam quis enim lobortis. Pharetra sit amet aliquam id diam maecenas ultricies mi. Nulla pharetra diam sit amet nisl suscipit. Bibendum at varius vel pharetra vel turpis nunc eget. Nulla pellentesque dignissim enim sit. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Tincidunt ornare massa eget egestas purus viverra accumsan. Placerat orci nulla pellentesque dignissim enim sit amet. Diam sit amet nisl suscipit adipiscing. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Rutrum quisque non tellus orci ac auctor augue.

Venenatis a condimentum vitae sapien. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Morbi tincidunt ornare massa eget egestas. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Id aliquet risus feugiat in ante metus dictum at tempor. Vel turpis nunc eget lorem dolor sed viverra. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Diam donec adipiscing tristique risus nec feugiat in fermentum. In ornare quam viverra orci sagittis. Sodales ut eu sem integer vitae. Commodo ullamcorper a lacus vestibulum sed arcu. Id ornare arcu odio ut sem nulla pharetra diam.

Eu sem integer vitae justo eget. Lectus mauris ultrices eros in cursus turpis. Convallis tellus id interdum velit. Tristique senectus et netus et malesuada fames. Diam donec adipiscing tristique risus nec. Ultricies mi quis hendrerit dolor magna eget est lorem. Dictumst quisque sagittis purus sit. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Sed viverra tellus in hac habitasse platea dictumst. Sit amet venenatis urna cursus. A diam maecenas sed enim ut sem. In hendrerit gravida rutrum quisque non tellus. Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. In vitae turpis massa sed. Cursus turpis massa tincidunt dui. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Suspendisse interdum consectetur libero id faucibus nisl. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Tortor dignissim convallis aenean et.

Malesuada fames ac turpis egestas sed tempus urna. Etiam tempor orci eu lobortis elementum. Tellus mauris a diam maecenas sed. In nisl nisi scelerisque eu ultrices. Nunc faucibus a pellentesque sit. Risus at ultrices mi tempus imperdiet. Pretium lectus quam id leo in vitae turpis. Magna sit amet purus gravida quis blandit. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Varius morbi enim nunc faucibus. Ut etiam sit amet nisl purus in mollis. Egestas erat imperdiet sed euismod nisi porta lorem. Vitae congue mauris rhoncus aenean vel elit scelerisque. Congue mauris rhoncus aenean vel. In mollis nunc sed id semper risus. Arcu vitae elementum curabitur vitae. Dui id ornare arcu odio ut sem nulla pharetra.

Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Elementum curabitur vitae nunc sed velit dignissim. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Egestas congue quisque egestas diam in arcu cursus euismod quis. Porttitor eget dolor morbi non arcu risus quis varius. Libero justo laoreet sit amet cursus. Donec et odio pellentesque diam volutpat commodo sed. Aliquam sem fringilla ut morbi tincidunt. Cras ornare arcu dui vivamus arcu felis bibendum ut. Sed risus ultricies tristique nulla aliquet enim tortor. Viverra justo nec ultrices dui sapien eget mi proin sed. Ut tellus elementum sagittis vitae et leo duis.

Egestas egestas fringilla phasellus faucibus scelerisque. Aliquet sagittis id consectetur purus ut faucibus. Urna nec tincidunt praesent semper feugiat nibh sed. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Sit amet nulla facilisi morbi. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Amet mattis vulputate enim nulla. Tempor orci eu lobortis elementum nibh. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Sit amet cursus sit amet dictum sit amet justo donec. Mi in nulla posuere sollicitudin aliquam. Amet facilisis magna etiam tempor orci eu. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Leo duis ut diam quam nulla porttitor massa id neque. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Sit amet cursus sit amet dictum. Tempus quam pellentesque nec nam aliquam sem et. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Aliquam etiam erat velit scelerisque in dictum. Cras sed felis eget velit aliquet sagittis id consectetur.

Laoreet id donec ultrices tincidunt arcu non. Id nibh tortor id aliquet lectus proin nibh nisl. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Eget magna fermentum iaculis eu non. Nulla facilisi cras fermentum odio. Sem viverra aliquet eget sit amet tellus. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Sit amet porttitor eget dolor morbi. Vitae purus faucibus ornare suspendisse sed nisi. Aliquet nec ullamcorper sit amet risus. Dictum non consectetur a erat nam at lectus. Sollicitudin tempor id eu nisl. Risus sed vulputate odio ut enim blandit volutpat maecenas volutpat.

Tellus at urna condimentum mattis pellentesque id nibh tortor id. Amet justo donec enim diam. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Id aliquet risus feugiat in ante metus dictum. Ultricies leo integer malesuada nunc vel risus. Dapibus ultrices in iaculis nunc sed augue lacus. Id diam maecenas ultricies mi eget mauris pharetra et. Etiam sit amet nisl purus in. Id consectetur purus ut faucibus pulvinar elementum. Id aliquet risus feugiat in. Eu sem integer vitae justo eget magna fermentum. Sed id semper risus in hendrerit. Bibendum neque egestas congue quisque egestas diam. Ut placerat orci nulla pellentesque dignissim enim. Tristique magna sit amet purus gravida.

Risus in hendrerit gravida rutrum quisque. Risus quis varius quam quisque. Nulla aliquet porttitor lacus luctus. Lorem mollis aliquam ut porttitor leo a. Orci porta non pulvinar neque. Eget egestas purus viverra accumsan. Ultrices mi tempus imperdiet nulla malesuada. Odio eu feugiat pretium nibh ipsum. Consequat interdum varius sit amet mattis vulputate enim. Hac habitasse platea dictumst quisque sagittis. Sit amet aliquam id diam maecenas ultricies mi. Arcu odio ut sem nulla. Cursus turpis massa tincidunt dui ut ornare lectus. Blandit cursus risus at ultrices. Tristique magna sit amet purus gravida quis blandit. Cras tincidunt lobortis feugiat vivamus at augue. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Varius quam quisque id diam vel quam elementum pulvinar. Sit amet massa vitae tortor condimentum lacinia.";
    }
}
